### ISSUE TITLE
[DOC-288] 21 CFR Part 11 Compliance

### ISSUE THREAD

**Issue by ElTimuro** [documenso/backlog#18]
- Regulation Details: https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfcfr/CFRSearch.cfm?CFRPart=11
- 21 CFR Part 11 Compliance would allow Documenso to be used in medical use cases like trial, patient waivers, and the medical equipment industry
- Since it's a complex regulation, support should be for self-hosted versions only in the beginning
- Longterm, this will probably be supported by the hosted version as well
- Features needed for this that are not part of any other use cases should be activatable by a "CFR21PART11_COMPLIANCE" feature flag

<sub>[DOC-288](https://linear.app/documenso/issue/DOC-288/21-cfr-part-11-compliance)</sub>

**Comment by ivoflipse** [comment]
Is there anything that can be done to help here?

**Comment by ElTimuro** [comment]
- @ivoflipse currently not. We are developing this internally with Vial.com and will share details soon
- We plan to publish the exact measures we took so others can learn from it
- Once we publish, feedback is very welcome
- You are free to look at the current repo, as we add all necessary features, but so far we don't have collection what belongs to 21 CFR
