### ISSUE TITLE
Global Language Support/ i18n

### ISSUE THREAD

**Issue by ElTimuro** [documenso/backlog#22]
- The aim is to support every language on earth with Documenso
- The Translations should ideally be community-supported to allow for global coverage without overloading the core team
- Something like https://inlang.com/ ParaglideJS if we don't decide to roll our own completely

**Comment by ElTimuro** [comment]
This could be useful: https://inlang.com/

**Comment by lodembeep** [comment]
Maybe consider Transifex ?
I do translations for bitcoin dot org and it is what we use.

**Comment by ElTimuro** [comment]
> Maybe consider Transifex ? I do translations for bitcoin dot org and it is what we use.

- will look into this
- Also: Thank you for your service contributing to bitcoin 🫡

**Comment by younes101020** [comment]
I have set up the internationalization structure and I have translated the marketing application by adding French, could someone review my pull request? If it is not accepted I would like to have some feedback that will allow me to improve thank you

pr: https://github.com/documenso/documenso/pull/1207

**Comment by mKoonrad** [comment]
Crowdin for localization will be the best!

**Comment by Mythie** [comment]
We settled on Lingui and CrowdIn, the project is now Public (?). We will have a later announcement with more details on the contribution process.

For now we support:
- English
- German
- Spanish
- French
