### ISSUE TITLE
[DOC-235] Third Party OAuth Support

### ISSUE THREAD

**Issue by ElTimuro** [documenso/backlog#6]
* OAuth is a secure and convenient way to access a service
* Apart from Google ([https://github.com/documenso/documenso/issues/106](https://github.com/documenso/documenso/issues/106)) what other providers should we support?
* OpenID Connect (OIDC)

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-235](https://linear.app/documenso/issue/DOC-235/third-party-oauth-support)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-235](https://linear.app/documenso/issue/DOC-235/third-party-oauth-support)</sub>

**Comment by floriant29** [comment]
Hi,
Support for Microsoft auth will be great, here are the available authentication methods :
- SAML authentication with Microsoft Entra ID : https://learn.microsoft.com/en-us/entra/architecture/auth-saml
- OAuth 2.0 authorization with Microsoft Entra ID : https://learn.microsoft.com/en-us/entra/architecture/auth-oauth2
- OpenID Connect authentication with Microsoft Entra ID : https://learn.microsoft.com/en-us/entra/architecture/auth-oidc

**Comment by Mythie** [comment]
We support this via OIDC for self-hosters and have our currently supported providers for the cloud version.

The intention later is to add support for SSO via OIDC or SAML on an organisation level once organisations actually exist.
